server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    sources:
      # The default Youtube source is now deprecated and won't receive further updates. Please use https://github.com/lavalink-devs/youtube-source#plugin instead.
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: false # warning: keeping HTTP enabled without a proxy configured could expose your server's IP address.
      local: false
    filters: # All filters are enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    password: "ganyuontopuwu"
    bufferDurationMs: 225
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 3
    opusEncodingQuality: 5
    resamplingQuality: MEDIUM
    trackStuckThresholdMs: 5000
    playerUpdateInterval: 3
    useSeekGhosting: true
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0" # LavaSrc - extra sources like deezer, spotify, etc. https://github.com/topi314/LavaSrc
      snapshot: false
    - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0" # https://github.com/topi314/LavaSearch
      snapshot: false
    - dependency: "com.dunctebot:skybot-lavalink-plugin:1.7.0" # https://github.com/DuncteBot/skybot-lavalink-plugin
      snapshot: false
    - dependency: "com.github.devoxin:lavadspx-plugin:0.0.5" # https://github.com/devoxin/LavaDSPX-Plugin
      repository: "https://jitpack.io"
      snapshot: false
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.0" # https://github.com/lavalink-devs/youtube-source
      snapshot: false
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.0.0" # https://github.com/topi314/LavaLyrics
      snapshot: false
    - dependency: "me.duncte123:java-lyrics-plugin:1.6.5" # https://github.com/DuncteBot/java-timed-lyrics
      snapshot: false
plugins:
  youtube:
    enabled: true
    # See: https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#using-oauth-tokens
    oauth:
      enabled: true
      # Uncomment the 'refreshToken' section when you get a valid refresh token.
      #refreshToken: "your account access token"
      skipInitialization: false
    # Only if you need/want use the pot data
    # See: https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#using-a-potoken
    #pot:
    #  token: "your pot token"
    #  visitorData: "the visitor data"
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    # See: https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#available-clients
    clients:
      - MUSIC
      - ANDROID_MUSIC
      - ANDROID_VR
      - WEB
      - MWEB
      - WEBEMBEDDED
      - TVHTML5EMBEDDED
    clientOptions:
      ANDROID_MUSIC:
        playback: false
        playlistLoading: false
        searching: false
        videoLoading: true
      ANDROID_VR:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: true
      MWEB:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: true
      MUSIC:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: false
      TVHTML5EMBEDDED:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      WEB:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: false
      WEBEMBEDDED:
        playback: false
        playlistLoading: false
        searching: false
        videoLoading: false
  lyrics:
    countryCode: us #country code for resolving isrc tracks
    geniusApiKey: "Your Genius Client Access Token" # leave this out to disable genius searching. Get your api key (Client Access Token) from https://genius.com/api-clients
  lavalyrics:
    sources:
      - spotify
      - youtube
      - deezerf
      - yandexMusic
  lavasrc:
    providers:
      - 'ytsearch:"%ISRC%"'
      - "ytmsearch:%QUERY%"
      - "ytsearch:%QUERY%"
      - "scsearch:%QUERY%"
      - "spsearch:%QUERY%"
    sources:
      spotify: true # Enable Spotify source
      applemusic: false # Enable Apple Music source
      deezer: false # Enable Deezer source
      yandexmusic: false # Enable Yandex Music source
      flowerytts: true # Enable Flowery TTS source
      youtube: true # Enable YouTube search source (https://github.com/topi314/LavaSearch)
      vkmusic: false # Enable Vk Music source
    lyrics-sources:
      spotify: false # Enable Spotify lyrics source
      deezer: false # Enable Deezer lyrics source
      youtube: true # Enable YouTube lyrics source
      yandexmusic: false # Enable Yandex Music lyrics source
      vkmusic: false # Enable Vk Music lyrics source
    youtube:
      countryCode: "US"
      playlistLoadLimit: 1 # The number of pages at 100 tracks each
      albumLoadLimit: 1 # The number of pages at 50 tracks each
      artistLoadLimit: 1 # The number of pages at 10 tracks each
    yandexmusic:
      accessToken: "your yandex token" # the token used for accessing the yandex music api. See https://github.com/TopiSenpai/LavaSrc#yandex-music
      playlistLoadLimit: 1 # The number of pages at 100 tracks each
      albumLoadLimit: 1 # The number of pages at 50 tracks each
      artistLoadLimit: 1 # The number of pages at 10 tracks each
    spotify:
      # clientId: "your client id"
      # clientSecret: "your client secret"
      # spDc: "your sp dc cookie" # the sp dc cookie used for accessing the spotify lyrics api
      countryCode: "US" # the country code you want to use for filtering the artists top tracks. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      playlistLoadLimit: 6 # The number of pages at 100 tracks each
      albumLoadLimit: 6 # The number of pages at 50 tracks each
      resolveArtistsInSearch: true # Whether to resolve artists in track search results (can be slow)
      localFiles: false # Enable local files support with Spotify playlists. Please note `uri` & `isrc` will be `null` & `identifier` will be `"local"`
    flowerytts:
      voice: "Olivia" # (case-sensitive) get default voice from here https://api.flowery.pw/v1/tts/voices
      translate: false # whether to translate the text to the native language of voice
      silence: 0 # the silence parameter is in milliseconds. Range is 0 to 10000. The default is 0.
      speed: 1.0 # the speed parameter is a float between 0.5 and 10. The default is 1.0. (0.5 is half speed, 2.0 is double speed, etc.)
      audioFormat: "mp3" # supported formats are: mp3, ogg_opus, ogg_vorbis, aac, wav, and flac. Default format is mp3
    dunctebot:
      ttsLanguage: "en-US"
      sources:
        getyarn: true # www.getyarn.io
        clypit: true # www.clyp.it
        tts: true # speak:Words to speak
        pornhub: true # should be self-explanatory
        reddit: true # should be self-explanatory
        ocremix: true # www.ocremix.org
        tiktok: true # tiktok.com
        mixcloud: true # mixcloud.com
        soundgasm: true # soundgasm.net
    applemusic:
      countryCode: "US" # the country code you want to use for filtering the artists top tracks and language. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      mediaAPIToken: "your apple music api token" # apple music api token
      # or specify an apple music key
      keyID: "your key id"
      teamID: "your team id"
      musicKitKey: |
        -----BEGIN PRIVATE KEY-----
        your key
        -----END PRIVATE KEY-----      
      playlistLoadLimit: 6 # The number of pages at 300 tracks each
      albumLoadLimit: 6 # The number of pages at 300 tracks each
    deezer:
      masterDecryptionKey: "your master decryption key" # the master key used for decrypting the deezer tracks. (yes this is not here you need to get it from somewhere else)
      # arl: "your deezer arl" # the arl cookie used for accessing the deezer api this is optional but required for formats above MP3_128
      formats: [ "FLAC", "MP3_320", "MP3_256", "MP3_128", "MP3_64", "AAC_64" ] # the formats you want to use for the deezer tracks. "FLAC", "MP3_320", "MP3_256" & "AAC_64" are only available for premium users and require a valid arl
    vkmusic:
      userToken: "your user token" # This token is needed for authorization in the api. Guide: https://github.com/topi314/LavaSrc#vk-music
      playlistLoadLimit: 1 # The number of pages at 50 tracks each
      artistLoadLimit: 1 # The number of pages at 10 tracks each
      recommendationsLoadLimit: 10 # Number of tracks
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
sentry:
  dsn: ""
  environment: ""
logging:
  file:
    max-history: 5
    max-size: 10MB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: true
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5